global:
  storageClass: standard
  postgresql:
    auth:
      username: "healenium_user"
      existingSecret: hlm-secret
      secretKeys:
        adminPasswordKey: adminPassword
        userPasswordKey: userPassword

primary:
  extraEnvVars:
    - name: POSTGRES_USER
      value: "healenium_user"
    - name: POSTGRES_DB
      value: "healenium"
  initdb:
    scripts:
      init_postgres.sh: |
        #!/bin/bash
        echo "Creating schema..."
        export PGPASSWORD="${POSTGRES_PASSWORD}"
        /opt/bitnami/postgresql/bin/psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "CREATE SCHEMA healenium AUTHORIZATION healenium_user;"
        echo "Checking if schema created..."
        /opt/bitnami/postgresql/bin/psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c "\dn"

persistence:
  enabled: true
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: "8Gi"
