{{- if .Values.hlmproxy.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hlmproxy.name }}
  labels:
    app: {{ include "healenium.fullname" . }}
    component: {{ .Values.hlmproxy.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.hlmproxy.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.hlmproxy.name }}
    spec:
      containers:
        - name: hlm-proxy
          image: "{{ .Values.hlmproxy.repository }}:{{ .Values.hlmproxy.tag }}"
          ports:
            - containerPort: {{ .Values.hlmproxy.port }}
              protocol: TCP
          env:
            - name: HEAL_ENABLED
              value: "{{ .Values.hlmproxy.healing.healenabled }}"
            - name: RECOVERY_TRIES
              value: "{{ .Values.hlmproxy.healing.recoverytries }}"
            - name: SCORE_CAP
              value: "{{ .Values.hlmproxy.healing.scorecap }}"
            - name: SELENIUM_SERVER_URL
              value: {{ .Values.hlmproxy.environment.selenium_server_url }}
            - name: APPIUM_SERVER_URL
              value: {{ .Values.hlmproxy.environment.appium_server_url }}
            - name: HEALENIUM_SERVICE
              value: "http://{{ .Values.hlmbackend.name }}:{{ .Values.hlmbackend.port }}"
            - name: HEALENIUM_SERVER_URL
              value: {{ .Values.hlmbackend.address }}
            - name: IMITATE_SERVICE
              value: "http://{{ .Values.imitator.name }}:{{ .Values.imitator.port }}"
            - name: HLM_LOG_LEVEL
              value: {{ .Values.hlmproxy.environment.hlm_log_level }}
          resources:
            requests:
              cpu: {{ .Values.hlmproxy.resources.requests.cpu }}
              memory: {{ .Values.hlmproxy.resources.requests.memory }}
            limits:
              cpu: {{ .Values.hlmproxy.resources.limits.cpu }}
              memory: {{ .Values.hlmproxy.resources.limits.memory }}
  {{- end }}
