{{- if .Values.ingress.enable }}
{{- $hlmBackendName := .Values.hlmbackend.name -}}
{{- $hlmImitatorName := .Values.imitator.name -}}
{{- $hlmProxyName := .Values.hlmproxy.name -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hlm-ingress
spec:
  rules:
{{ if .Values.ingress.usedomainname }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths: 
      - path: /healenium
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmBackendName }}
            port:
              name: headless
      - path: /imitate
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmImitatorName }}
            port:
              name: headless
      - path: /docs
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmImitatorName }}
            port:
              name: headless
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmProxyName }}
            port:
              name: headless
  {{- end -}}
{{ else }}
  - http:
      paths: 
      - path: /healenium
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmBackendName }}
            port:
              name: headless
      - path: /imitate
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmImitatorName }}
            port:
              name: headless
      - path: /docs
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmImitatorName }}
            port:
              name: headless
      - path: /
        pathType: Prefix  
        backend:
          service:
            name: {{ $hlmProxyName }}
            port:
              name: headless
{{ end }}
{{- end }}