apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.imitator.name }}
  labels:
    app: {{ include "healenium.fullname" . }}
    component: {{ .Values.imitator.name }}
spec:
  ports:
  - name: headless
    protocol: TCP
    port: {{ .Values.imitator.port }}
    targetPort: {{ .Values.imitator.port }}
  selector:
    app: {{ .Values.imitator.name }}
  type: ClusterIP