apiVersion: v1
kind: PersistentVolume
metadata:
  name: hlm-proxy-logs-pv
  labels:
    type: hlm-proxy-logs
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/proxy/logs"