apiVersion: v1
kind: PersistentVolume
metadata:
  name: screenshots-pv
  labels:
    type: screenshots
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/screenshots"