apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hlm-backend-logs-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      type: hlm-backend-logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi