apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hlmbackend.name }}
  labels:
    app: {{ include "healenium.fullname" . }}
    component: {{ .Values.hlmbackend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.hlmbackend.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.hlmbackend.name }}
    spec:
      initContainers:
        - name: create-schema
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              PGPASSWORD={{ .Values.postgresql.endpoint.password }} psql -h {{ .Values.postgresql.endpoint.address }} -U {{ .Values.postgresql.endpoint.user }} -d {{ .Values.postgresql.endpoint.dbName }} -c "CREATE SCHEMA IF NOT EXISTS {{ .Values.postgresql.endpoint.schema }};" || true
      containers:
        - name: hlm-backend
          image: "{{ .Values.hlmbackend.repository }}:{{ .Values.hlmbackend.tag }}"
          ports:
            - containerPort: {{ .Values.hlmbackend.port }}
              protocol: TCP
          env:
            - name: SPRING_POSTGRES_DB
              value: {{ .Values.postgresql.endpoint.dbName }}
            - name: SPRING_POSTGRES_SCHEMA
              value: {{ .Values.postgresql.endpoint.schema }}
            - name: SPRING_POSTGRES_USER
              value: {{ .Values.postgresql.endpoint.user }}
            - name: SPRING_POSTGRES_PASSWORD
              value: {{ .Values.postgresql.endpoint.password }}
            - name: SPRING_POSTGRES_DB_HOST
              value: {{ .Values.postgresql.endpoint.address }}
            - name: SPRING_LIQUIBASE_LIQUIBASESCHEMA
              value: {{ .Values.postgresql.endpoint.schema }}
            - name: SPRING_LIQUIBASE_DEFAULTSCHEMA
              value: {{ .Values.postgresql.endpoint.schema }}
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: {{ .Values.postgresql.endpoint.schema }}
            - name: KEY_SELECTOR_URL
              value: "{{ .Values.hlmbackend.environment.key_selector_url }}"
            - name: COLLECT_METRICS
              value: "{{ .Values.hlmbackend.environment.collect_metrics }}"
            - name: FIND_ELEMENTS_AUTO_HEALING
              value: "{{ .Values.hlmbackend.environment.find_elements_auto_healing }}"
            - name: HLM_LOG_LEVEL
              value: {{ .Values.hlmbackend.environment.hlm_log_level }}
          resources:
            requests:
              cpu: {{ .Values.hlmbackend.resources.requests.cpu }}
              memory: {{ .Values.hlmbackend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.hlmbackend.resources.limits.cpu }}
              memory: {{ .Values.hlmbackend.resources.limits.memory }}
