{{- if .Values.hlmproxy.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hlmproxy.name }}
  labels:
    app: {{ include "healenium.fullname" . }}
    component: {{ .Values.hlmproxy.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.hlmproxy.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.hlmproxy.name }}
    spec:
      containers:
        - name: hlm-proxy
          image: "{{ .Values.hlmproxy.repository }}:{{ .Values.hlmproxy.tag }}"
          ports:
            - containerPort: {{ .Values.hlmproxy.port }}
              protocol: TCP
          env: 
            - name: HEAL_ENABLED
              value: "{{ .Values.hlmproxy.healing.healenabled }}"
            - name: RECOVERY_TRIES
              value: "{{ .Values.hlmproxy.healing.recoverytries }}"
            - name: SCORE_CAP
              value: "{{ .Values.hlmproxy.healing.scorecap }}"
            - name: SELENIUM_HOST
              value: "{{ .Values.hlmproxy.environment.selenium_host }}"
            - name: SELENIUM_PORT
              value: "{{ .Values.hlmproxy.environment.selenium_port }}"
            - name: SELENIUM_URL
              value: {{ .Values.hlmproxy.environment.selenium_url }}
            - name: HEALENIUM_HOST
              value: {{ .Values.hlmbackend.name }}
            - name: IMITATE_HOST
              value: {{ .Values.imitator.name }}
          resources:
            requests:
              cpu: {{ .Values.hlmproxy.resources.requests.cpu }}
              memory: {{ .Values.hlmproxy.resources.requests.memory }}
            limits:
              cpu: {{ .Values.hlmproxy.resources.limits.cpu }}
              memory: {{ .Values.hlmproxy.resources.limits.memory }}
{{- end }}
