name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'requirements.yaml'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm Chart
        run: |
          mkdir -p .cr-release-packages
          helm package . -d .cr-release-packages

      - name: Upload Release and Update Index
        run: |
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          
          # Install chart-releaser
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz
          rm -f cr.tar.gz
          
          # Upload chart to GitHub releases
          ./cr upload -o "$owner" -r "$repo" -t "${{ secrets.GITHUB_TOKEN }}"
          
          # Update index and push to gh-pages
          ./cr index -o "$owner" -r "$repo" -c https://healenium.github.io/kubernetes -i index.yaml -t "${{ secrets.GITHUB_TOKEN }}" --push

