name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'requirements.yaml'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Prepare charts directory structure
        run: |
          mkdir -p .cr-release-packages
          mkdir -p charts/healenium
          cp -r Chart.yaml values.yaml requirements.yaml templates postgresql charts/healenium/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

